name: stocks-playground
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - bqplot
  - jupyter
  - nb_conda
  - pip
  - jupyter_contrib_nbextensions
  - pip:
      - googlefinance.client
      - streamlit
      - yfinance
      - pandas_datareader
